basePath: /
host: localhost:8080
info:
  contact: {}
  description: IM 即时通讯项目 API 文档
  title: ginchat API
  version: "1.0"
paths:
  /index:
    get:
      description: 返回欢迎信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 首页
      tags:
      - 首页
  /user/AddFriend:
    post:
      parameters:
      - description: 当前用户ID
        in: formData
        name: userId
        required: true
        type: integer
      - description: 目标好友ID
        in: formData
        name: targetId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 添加好友
      tags:
      - 用户管理
  /user/CreateUser:
    get:
      parameters:
      - description: 用户名
        in: query
        name: name
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      - description: 确认密码
        in: query
        name: repassword
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 新增用户
      tags:
      - 用户管理
  /user/DeleteUser:
    get:
      parameters:
      - description: id
        in: query
        name: id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 删除用户
      tags:
      - 用户管理
  /user/FindUserByNameAndPassword:
    post:
      parameters:
      - description: 用户名
        in: query
        name: name
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 登入
      tags:
      - 用户管理
  /user/GetChatRecord:
    get:
      parameters:
      - description: 当前用户ID
        in: formData
        name: id
        required: true
        type: integer
      - description: 目标用户ID
        in: formData
        name: targetId
        required: true
        type: integer
      - description: 页码
        in: formData
        name: page
        required: true
        type: integer
      - description: 每页数量
        in: formData
        name: pageSize
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 获取与某个用户的聊天记录
      tags:
      - 用户管理
  /user/GetUserList:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 所有用户
      tags:
      - 用户管理
  /user/SearchFriend:
    get:
      parameters:
      - description: 用户ID
        in: query
        name: userid
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 获取好友列表
      tags:
      - 用户管理
  /user/UpdateUser:
    post:
      parameters:
      - description: id
        in: formData
        name: id
        type: string
      - description: 用户名
        in: formData
        name: name
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      - description: 邮箱
        in: formData
        name: email
        required: true
        type: string
      - description: 手机号
        in: formData
        name: phone
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 修改 用户
      tags:
      - 用户管理
swagger: "2.0"
